# this is a deployment file for ckb testnet

[[cells]]
name = "spore-dob-0"
enable_type_id = true
location = { file = "target/riscv64imac-unknown-none-elf/release/spore-dob-0" }

# The lock script set to output cells
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x3ec4289e098feea12d0d566d56bfceab9e34a996"
hash_type = "type"
